python main.py --gpus "0," --max_epochs 1  \
    --data_class REDataset \
    --litmodel_class INFERLitModel \
    --model_class Inference \
    --task_name interactive \
    --batch_size 1 \
    --model_name_or_path bert-base-chinese \
    --ner_model_name_or_path output/ner \
    --seq_model_name_or_path output/seq \
    --max_seq_length 512 \
    --check_val_every_n_epoch 1 \
    --data_dir ./dataset/ske