CUDA_VISIBLE_DEVICES=0 python main.py --gpus "0," --max_epochs 1  \
    --data_class REDataset \
    --litmodel_class RELitModel \
    --model_class BertForNER \
    --task_name ner \
    --limit_train_batches 10 \
    --limit_val_batches 10 \
    --limit_test_batches 10 \
    --batch_size 16 \
    --model_name_or_path bert-base-chinese \
    --max_seq_length 512 \
    --check_val_every_n_epoch 1 \
    --data_dir ./dataset/ske 